title: |
  <span>Voeg Moppersmurf toe als vriend op Facebook</span> en maak kans op een pink Xperia U of De Smurfen in 3D<sup>TM</sup> op dvd.
button: Word vriend van Moppersmurf 
twitter_url: https://twitter.com/de_moppersmurf
facebook_url: http://www.facebook.com/demopper
regulation_url: 
regulations: reglement