site_title: LES SCHTROUMPFS 2
title: |
  <span>DEVIENS AMI AVEC LE SCHTROUMPF GROGNON SUR FACEBOOK</span> ET GAGNE PEUT-ÊTRE UN XPERIA U ROSE OU LE DVD DES SCHTROUMPFS EN 3D<sup>TM</sup>.
button: deviens ami avec le schtroumpf grognon
twitter_url: https://twitter.com/Le_S_Grognon
facebook_url: http://www.facebook.com/legrognon
regulation_url: 
regulations: règlement